### ISSUE TITLE
Full system monitoring setup does not work for API

### ISSUE THREAD

**Issue by LpKronek** [dataiku/dkumonitor#2]
Here is the log : 

[+] Saving installation log to /home/dataiku/api/run/install.log
/home/dataiku/kit_dir/dataiku-dss-4.3.2/scripts/_install-monitoring-integration.sh: line 119: /home/dataiku/api/bin/dku: No such file or directory

**Comment by duckie** [comment]
Hi, known issue, fix have been merged for next release.

Beware this has nothing to do with the dkumonitor : the monitoring integration is a DSS feature.
